### ISSUE TITLE
Artifacts Issue

### ISSUE THREAD

**Issue by Yamarajsha** [dougg3/obs-ios-camera-source#12]
Hello,

May you please update the artifacts? The last date says expired and no longer available to download it

I tried to build without it and cmake shows an error

**Comment by dougg3** [comment]
Thanks for letting me know! I'm going to change it so that I store them as releases rather than artifacts from GitHub Actions.

**Comment by dougg3** [comment]
@Yamarajsha this should be fixed now. See the Releases section -- these binaries will never expire. I also ran into the CMake error you reported. It appears that OBS has changed the way that the plugin needs to be imported. To get it working for now, I've changed the build workflow to grab the last version of libobs prior to the CMake change. I will also update the build instructions. Long term, I need to update CMakeLists.txt to build the plugin the "new way" that OBS wants.

Thanks again for pointing out the problem!
