### ISSUE TITLE
CMake still shows an error...

### ISSUE THREAD

**Issue by Yamarajsha** [dougg3/obs-ios-camera-source#13]
I don't know if this error came from ArchLinux or I did something wrong... I tried with both Ubuntu 18/20 and it shows the same line error. I pasted the terminal and the log file for better references... Sorry to bother you so much!! =(

> [arkander@Astaroth build]$ cmake .. -DLIBOBS_INCLUDE_DIR=~/Downloads/obs-studio/cmake
> -- The C compiler identification is GNU 11.2.0
> -- The CXX compiler identification is GNU 11.2.0
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: /usr/bin/cc - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /usr/bin/c++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Could NOT find Libobs (missing: LIBOBS_LIB) 
> CMake Error at external/FindLibObs.cmake:106 (message):
>   Could not find the libobs library
> Call Stack (most recent call first):
>   CMakeLists.txt:10 (include)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/arkander/Downloads/obs-ios-camera-source/build/CMakeFiles/CMakeOutput.log".

[CMakeOutput.log](https://github.com/dougg3/obs-ios-camera-source/files/8459764/CMakeOutput.log)

**Comment by dougg3** [comment]
Did you do the `git clone -b 27.2.1 https://github.com/obsproject/obs-studio.git` command first, from your ~/Downloads directory? The error you're seeing seems to be implying that it's not there for some reason.

**Comment by Yamarajsha** [comment]
Well, I did it again before answer you now and it stopped in the same line... 

> [arkander@Astaroth ~]$ git clone -b 27.2.1 https://github.com/obsproject/obs-studio.git
> Cloning into 'obs-studio'...
> remote: Enumerating objects: 80095, done.
> remote: Counting objects: 100% (5/5), done.
> remote: Compressing objects: 100% (5/5), done.
> remote: Total 80095 (delta 0), reused 4 (delta 0), pack-reused 80090
> Receiving objects: 100% (80095/80095), 56.00 MiB | 14.19 MiB/s, done.
> Resolving deltas: 100% (54094/54094), done.
> Note: switching to 'acad9dbaf7bcf8f567c3e5c613411ca04ba92fa9'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by switching back to a branch.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -c with the switch command. Example:
> 
>   git switch -c <new-branch-name>
> 
> Or undo this operation with:
> 
>   git switch -
> 
> Turn off this advice by setting config variable advice.detachedHead to false


This is the message when I make that command line; I assume an error by myself or something I missed

**Comment by dougg3** [comment]
That all looks fine and the git clone is successful. However it doesn’t look like you are in your ~/Downloads directory when running the command, so that might explain why cmake isn’t finding it.

**Comment by Yamarajsha** [comment]
I found my error... Sorry for the inconvenient
