### ISSUE TITLE
Cant see iPhone

### ISSUE THREAD

**Issue by repentandliveholy** [dougg3/obs-ios-camera-source#7]
Thanks for plugin for obs linux!

I have installed it on Ubuntu 20.04 (snap) and I can see it (snap plugins folder is different from default...) 

It is appered in OBS and opens but CANT see my iPhone 8 with obs.iphone paid program installed which works on Windows obs. 

What can I do?

During compile it was some warnings but succesufully compiled to files: *ini and *so

Please, help!

**Comment by repentandliveholy** [comment]
I open a program on iPhone, connect to pc, agreen to pop-up message - but can't see...

**Comment by repentandliveholy** [comment]
![Uploading Screenshot from 2021-03-12 11-55-48.png…]()

**Comment by repentandliveholy** [comment]
mbl@mbl-ThinkPad-P52:~/Downloads/obs-ios-camera-source/build$ cmake .. -DLIBOBS_INCLUDE_DIR=~/Downloads/obs-studio/cmake
-- Configuring done
CMake Warning (dev) in CMakeLists.txt:
  AUTOGEN: No valid Qt version found for target obs-ios-camera-source.
  AUTOMOC and AUTOUIC disabled.  Consider adding:

    find_package(Qt<QTVERSION> COMPONENTS Widgets)

  to your CMakeLists.txt file.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  AUTOGEN: No valid Qt version found for target portal.  AUTOMOC and AUTOUIC
  disabled.  Consider adding:

    find_package(Qt<QTVERSION> COMPONENTS Widgets)

  to your CMakeLists.txt file.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  AUTOGEN: No valid Qt version found for target libusbmuxd.  AUTOMOC and
  AUTOUIC disabled.  Consider adding:

    find_package(Qt<QTVERSION> COMPONENTS Widgets)

  to your CMakeLists.txt file.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  AUTOGEN: No valid Qt version found for target libplist.  AUTOMOC and
  AUTOUIC disabled.  Consider adding:

    find_package(Qt<QTVERSION> COMPONENTS Widgets)

  to your CMakeLists.txt file.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  AUTOGEN: No valid Qt version found for target libcnary.  AUTOMOC and
  AUTOUIC disabled.  Consider adding:

    find_package(Qt<QTVERSION> COMPONENTS Widgets)

  to your CMakeLists.txt file.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/mbl/Downloads/obs-ios-camera-source/build

**Comment by repentandliveholy** [comment]
Alson tryed this simple method, but steel it doesnt show an iPhone in OBS\iPhone

_Ubuntu 20.04 (and possibly other distros) and 18.04
Go to the actions section of this repository and click on the latest workflow that finished successfully. Then download the artifact that corresponds to your version. After downloading, place the zip file in your home directory and run:

unzip plugin-ubuntu-*.zip
You must have the unzip package installed for this to work: sudo apt install unzip._

**Comment by repentandliveholy** [comment]
FINALLY IT WORKED!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! THANKS DOUG!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
THANKS GOD!

**Comment by repentandliveholy** [comment]
The main reason was that my OBS was not default but with alot of plugins. I just removed it and istaled off.version and now it WORKS

**Comment by dougg3** [comment]
Glad you figured it out!
